---
- name: get checkpoint information create by kz
  cli_command: 
    command: "{{item}}"

  register: result
  loop: "{{lookup('list', hostvars[inventory_hostname]['input_command'])}}"
  
- name: call save result function
  #include_tasks: save_result.yml
  debug: 
    msg: "{{cp_result.results}}"
  tags: print_output
  
  
- name: save checkpoint result into log file
  local_action: lineinfile line="\n <div>style='background-color:LightGray;'. <strong>\n 
  ********************************************************************
  \n ***Host_ip*{{inventory_hostname}}
  \n ***Domain*{{hostvars[inventory_hostname]['domain']}}
  \n *** run command* {{hostvars[inventory_hostname]['input_command'][my_idx]}}</strong> \n 
  *********************************************************************
  </div> \n
  \n {{item.stdout}} \n 
  ********************************************************************\n 
    insertafter=EOF
    dest="{{hostvars['localhost']['dest_file']}}"
  loop: "{{cp_result.results}}"
  loop_control: 
    index_var: my_idx
    
    