- name: get juniper information create by kz
  nxos_command: 
    commands: "{{hostvars[inventory_hostname]['input_command']}}"
  register: result
  
  
- name: call save result function
  include_tasks: save_result.yml